;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=True
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="InputTag.Native.Jump",NewTagName="InputTag.Ability.Jump")
+GameplayTagRedirects=(OldTagName="InputTag.Ability",NewTagName="InputTag.Action")
+GameplayTagList=(Tag="Ability",DevComment="")
+GameplayTagList=(Tag="Ability.Action",DevComment="")
+GameplayTagList=(Tag="Ability.Action.Dash",DevComment="")
+GameplayTagList=(Tag="Ability.Action.Jump",DevComment="")
+GameplayTagList=(Tag="Ability.Action.WebSwing",DevComment="")
+GameplayTagList=(Tag="Character",DevComment="")
+GameplayTagList=(Tag="Character.Default",DevComment="")
+GameplayTagList=(Tag="Character.Spidy",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Character",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Character.DamageTaken",DevComment="")
+GameplayTagList=(Tag="InputTag.Ability.Dash",DevComment="")
+GameplayTagList=(Tag="InputTag.Ability.Jump",DevComment="")
+GameplayTagList=(Tag="InputTag.Ability.WeaponFire",DevComment="")
+GameplayTagList=(Tag="InputTag.Ability.WebSwing",DevComment="")
+GameplayTagList=(Tag="InputTag.Native",DevComment="")
+GameplayTagList=(Tag="InputTag.Native.Look",DevComment="")
+GameplayTagList=(Tag="InputTag.Native.Move",DevComment="")
+GameplayTagList=(Tag="Item",DevComment="")
+GameplayTagList=(Tag="Item.HealthPotion",DevComment="")
+GameplayTagList=(Tag="Item.StaminaPotion",DevComment="")
+GameplayTagList=(Tag="State",DevComment="")
+GameplayTagList=(Tag="State.Jump",DevComment="")
+GameplayTagList=(Tag="State.Move",DevComment="")
+GameplayTagList=(Tag="Status.Walk",DevComment="")

